### ISSUE TITLE
Feeds returning 403

### ISSUE THREAD

**Issue by jonallured** [feedjira/feedjira#251]
Got a weird report from @davidpots:

```
http://neutral.fm/episodes?format=rss
http://atp.fm/episodes?format=rss
http://accidentalhousewives.com/feed/
http://theaccidentalpodcast.squarespace.com/podcast?format=rss
http://www.screencast.com/users/TheZoo/folders/Alf%27s+Zoo/itunes
```

> When I try to parse these with Feedzirra, I get a 403.

https://gist.github.com/davidpots/fced027d4d6039222af6

Nothing jumped out at me immediately, so this needs further research.

**Comment by jkpchang** [comment]
Is there a way to set User Agent using the current code base? I tried:

Feedjira::Feed.fetch_and_parse uri, user_agent: UA

but seems like fetch_and_parse is only accepting one parameter now. Please help. I am getting 403 error when running Feedjira against machines that detects robots.

**Comment by amatriain** [comment]
I looked at the code and yes, it seems that with the recent switch to Faraday for HTTP fetching, Feedjira no longer allows setting a user-agent. 

As a workaround, you can fetch the feed's XML with an HTTP gem like RestClient, Curb, Net::HTTP or others, either directly or through Faraday if supported. Most of those gems if not all allow setting the UA: there's a Curb example a few posts above, look at the specific documentation for the gem you finally decide upon.

Once you have the XML in the HTTP response, parse it with ```Feedjira::Feed.parse```. The result is the same as invoking ```fetch_and_parse```, but you take care of the fetching part instead of delegating in Feedjira.
