### ISSUE TITLE
Parsing enclosure tags 

### ISSUE THREAD

**Issue by lustremedia** [feedjira/feedjira#258]
When I parse an enclosure tag from a wordpress feed, additional meta information such as type and length is lost.
A rss item enclosure tag looks as follows:
```xml
<item>
<enclosure url="http://example.com/mypodcast.mp3" length="6431473" type="audio/mpeg" />
</item>
```
Feedjira puts only the url information http://example.com/mypodcast.mp3 into an @image attribute 
```xml
<Feedjira::Parser::RSSEntry  @image="http://example.com/mypodcast.mp3" >
```
Type and length is not provided. Is there a reason for that?

**Comment by jonallured** [comment]
Sounds like what you want is the `Feedjira::Parser::ITunesRSSItem`:

https://github.com/feedjira/feedjira/blob/master/lib/feedjira/parser/itunes_rss_item.rb

Without knowing the specific feed you are parsing, my guess is that it doesn't properly present itself as an iTunes feed, so Feedjira isn't automatically parsing it using that parser. You can force Feedjira to use a particular parser like so:

```ruby
xml = Feedjira::Feed.fetch_raw 'http://example.com/feed.xml'
feed = Feedjira::Feed.parse_with Feedjira::Parser::ITunesRSS, xml
```

Hope that helps!
Jon

**Comment by lustremedia** [comment]
Hi Jon,

I am not parsing an iTunes Feed, but rather a simple wordpress rss 2.0 feed which includes media elements such as audio or video or image files in an enclosure tag (as can be seen above). Wordpress automatically outputs enclosure tags and generates the right metadata according to the media type.

Cheers,
LM

**Comment by jonallured** [comment]
Right, and that's why Feedjira is using the default `Feedjira::Parser::RSSEntry` parser rather than a more appropriate one. If you want to grab the `length` and `type` attributes of the `enclosure` element, you're going to have to do something that isn't default Feedjira behavior.

My suggestion is to force parsing with a more appropriate parser for your use-case, but you can also use the `Feedjira::Feed.add_common_feed_entry_element` if you prefer. I don't have an example feed url to test this with, but I think it would be something like this:

```ruby
Feedjira::Feed.add_common_feed_entry_element('enclosure', { value: :length, as: :enclosure_length })
Feedjira::Feed.add_common_feed_entry_element('enclosure', { value: :type, as: :enclosure_type })
feed = Feedjira::Feed.fetch_and_parse 'http://example.com/feed.xml'
feed.entries.first.enclosure_length # => 6431473
feed.entries.first.enclosure_type # => "audio/mpeg"
```

What I'm trying to express is that default Feedjira behavior isn't going to do what you're trying to accomplish, but that there are a couple ways you can use the library to work with your non-standard situation.

Thanks!
Jon

**Comment by lustremedia** [comment]
Ok great! Thanks for the heads up!
