### ISSUE TITLE
Some entries missed with this feed

### ISSUE THREAD

**Issue by mahemoff** [feedjira/feedjira#263]
Not sure why this happens:

```
> Feedjira::Feed.fetch_and_parse('http://feeds.feedburner.com/andymoormoormusic').entries.last.title
"Moor Music Episode 126"
```

Latest title at present is Episode 136. The entries count also reflects that it stops at 126. The feed sems to be valid but maybe I missed something.

**Comment by jonallured** [comment]
Hmmm, I just tried to reproduce this and here's what I got:

```ruby
Feedjira::Feed.fetch_and_parse('http://feeds.feedburner.com/andymoormoormusic').entries.last.title
# => "Moor Music Episode 138"
```

I'm not sure what's going on, but maybe they fixed whatever was causing your issue?

**Comment by mahemoff** [comment]
Odd. Still seeing it here. I actually tried it on a [fresh Vagrant instance](https://github.com/rails/rails-dev-box) just now. This is with Feedjira 1.6.0. Curl shows the missing posts up to episode 138.

**Comment by amatriain** [comment]
I'm also getting Episode 126 as the last entry.

@mahemoff , that feed is not even valid XML. Look at what the W3C validator says: 

http://validator.w3.org/check?uri=http%3A%2F%2Ffeeds.feedburner.com%2Fandymoormoormusic

```
Line 2592, Column 9: character "&" is the first character of a delimiter but occurred as data
Line 2601, Column 39: character "&" is the first character of a delimiter but occurred as data
Line 2648, Column 15: cannot generate system identifier for general entity "amp:"
etc...
```

Basically Feedjira correctly parses up to episode 126. Episode 127 has unescaped ```&``` characters in the ```<itunes:summary>``` content, those should be escaped to ```&amp;``` (previous entries do it). After that in Episode 129 you get another big error: an ```&``` wrongly escaped as ```&amp:``` instead of ```&amp;```. There are more errors after that if you look at the validator.

Episode 126 is the last valid entry in that feed. Feedjira cannot parse the following ones so they are ignored. Those errors cannot be fixed by Feedjira, the feed author should fix them.

Now I'm intrigued by why @jonallured is getting Episode 138 as the last entry...

**Comment by krasnoukhov** [comment]
@amatriain I believe this is because @jonallured has `ox` installed so SAXMachine uses it as a default handler.

```ruby
2.1.2 :001 > require "feedjira"
 => true 
2.1.2 :002 > SAXMachine.handler = :nokogiri
 => :nokogiri 
2.1.2 :003 > Feedjira::Feed.fetch_and_parse('http://feeds.feedburner.com/andymoormoormusic').entries.last.title
 => "Moor Music Episode 126" 
2.1.2 :004 > SAXMachine.handler = :ox
 => :ox 
2.1.2 :005 > Feedjira::Feed.fetch_and_parse('http://feeds.feedburner.com/andymoormoormusic').entries.last.title
 => "Moor Music Episode 138" 
2.1.2 :006 > 
```

So basically `ox` might be a better choice on MRI since it handles invalid XML better.

**Comment by mahemoff** [comment]
Thanks. I didn't realise the SAX processing is pluggable, so that's useful. It would be useful if there was a warning in case of SAX errors but I'm guessing that info is not available to Feedjira anyway. Closing this.
