### ISSUE TITLE
"ArgumentError: invalid byte sequence in UTF-8" during an attempt to parse a feed encoded in windows-1251

### ISSUE THREAD

**Issue by azangru** [feedjira/feedjira#278]
I'm working on an app that needs to parse rss feeds of various media outlets.

I was getting an error `gems/feedjira-1.6.0/lib/feedjira/feed.rb:237: warning: uncaught exception from callback`, and today I got to prying into it. It seems that at least one feed, that of a Russian newspaper *Novaya Gazeta*, is encoded in `windows-1251`. Here is what happens during its parsing: 

```
    314:         curl.on_success do |c|
    315:           xml = decode_content(c)
 => 316:           klass = determine_feed_parser_for_xml(xml)
    317: 
    318:           if klass
    319:             begin
    320:               feed = parse_with klass, xml, &on_parser_failure(url)
```

The `xml` object generated on line 315 begins like so:

```
<?xml version=\"1.0\" encoding=\"windows-1251\"?>\n<rss version=\"2.0\" xmlns:content=\"http://purl.org/rss/1.0/modules/content/\">
```

The encoding is clearly "windows-1251". And yet if I query the xml object about its encoding:

```
xml.encoding
```

the result is UTF-8.

So the gem thinks that the decoded content is in UTF-8 and passes it to the `determine_feed_parser_for_xml` method, which then fails:

```
klass = determine_feed_parser_for_xml(xml)


[11] pry(Feedjira::Feed)> determine_feed_parser_for_xml(xml)
ArgumentError: invalid byte sequence in UTF-8
from /home/andrey/.rvm/gems/ruby-2.1.3@mediaratings/gems/feedjira-1.6.0/lib/feedjira/parser/rss_feed_burner.rb:17:in `able_to_parse?'
```

Which causes the whole callback to fail, and I am not sure how to fix this problem. Perhaps you could advise?

The problematic feed for testing is: http://www.novayagazeta.ru/rss/all.xml

**Comment by jonallured** [comment]
Hey @azangru,

Feedjira doesn't do anything with the encoding attribute you mentioned - whatever comes back from `curb` when the request is made is what we're trying to parse. We need to figure out how to get the XML to come through as a properly encoded Ruby string.

Here's how it works when a feed's encodings line up:

```ruby
> xml = Feedjira::Feed.fetch_raw 'http://feedjira.com/blog/feed.xml'
> xml.encoding
# => #<Encoding:ASCII-8BIT>
> feed = Feedjira::Feed.parse xml
> feed.title
# => "Feedjira Blog"
```

We can separate the xml fetching from the xml parsing. Now we just need to get your feed into a properly encoded string:

```ruby
> xml = Feedjira::Feed.fetch_raw 'http://www.novayagazeta.ru/rss/all.xml'
> xml.encoding
# => #<Encoding:UTF-8>
> encoded_xml = xml.encode!('Windows-1251')
# Encoding::InvalidByteSequenceError: "\xCD" followed by "\xEE" on UTF-8
```

I'm not sure why that doesn't work. Maybe the feed claims `Windows-1251`, but isn't? We can try to force it.

```ruby
> xml = Feedjira::Feed.fetch_raw 'http://www.novayagazeta.ru/rss/all.xml'
> xml.encoding
# => #<Encoding:UTF-8>
> forced_xml = xml.force_encoding('Windows-1251')
> forced_xml.encoding
# => #<Encoding:Windows-1251>
> feed = Feedjira::Feed.parse forced_xml
> feed.title
# => "\xCD\xEE\xE2\xE0\xFF \xC3\xE0\xE7\xE5\xF2\xE0 - NovayaGazeta.ru"
```

We're past the parse error, but that output is non-sense. This is where I'm stuck - if anyone else has any insight, it would be much appreciated!

**Comment by amatriain** [comment]
@jonallured when you try to do ```xml.encode!('Windows-1251')``` it fails because it thinks the string is internally encoded in utf-8 and attempts to convert it to win-1251. However the string is actually encoded in win-1251, so the encoding fails because some byte sequences are not valid utf-8 (but they are valid win-1251 of course).

What you do later, ```xml.force_encoding('Windows-1251')```, is correct. The method name ```force_encoding``` is a bit misleading: it doesn't actually change the internal representation of the string at all, the only thing it does is to let ruby know that the string is actually a windows-1251 encoded string. 

Once ruby is aware of the actual encoding of the string, it can be passed to Feedjira::Feed for parsing, as you've done. The output you get is not nonsense at all, it's just that it's encoded in windows-1251, you have to convert it to utf-8 before printing if you want to see pretty cyrillic characters :) (it seems a limitation of the ruby console is that it expects utf-8 characters for printing; I want to stress that the feed title at that point is correct, however, and you can handle it in your program as long as ruby is aware that its encoding is win-1251, you don't have to convert it to utf-8 except if you only want to handle utf-8 in your app, I guess)

```
> feed.title
 => "\xCD\xEE\xE2\xE0\xFF \xC3\xE0\xE7\xE5\xF2\xE0 - NovayaGazeta.ru" 
> feed.title.encoding
 => #<Encoding:Windows-1251>
> puts feed.title.encode 'utf-8'
Новая Газета - NovayaGazeta.ru
```

**Comment by amatriain** [comment]
To summarize: if you know the encoding of the feed, it's easy to handle it:

- fetch the feed xml with an HTTP client: ```fetch_raw```, RestClient, a Faraday-supported gem, whatever, and store it into a string (e.g. ```xml```)
- make ruby aware of the actual encoding of the response, assuming you know it: ```xml.force_encoding <actual encoding>```
- pass the string with the correct encoding to Feedjira: ```feed = Feedjira::Feed.parse xml```
- be aware that the parsed entries, feed title etc will be in the same encoding as the feed xml, which is not necessarily utf-8. It may be a good idea to convert those strings to utf-8 before passing them to other parts of your program, for consistency's sake; e.g. ```xml.title.encode! 'utf-8'```

All of the above assumes you **already know the feed encoding**. That may not be trivial in some cases. As far as I know there are two ways the feed server can tell you about the encoding:

1. in the ```Content-type``` HTTP header. E.g. the following header
```Content-Type: text/html; charset:gbk;```
is saying that the response is a GBK encoded string. Note that the ```Content-type``` header does not necessarily include charset data, in fact @azangru's example didn't. The HTTP spec says the default in this case is ISO-8859-1, but this is often ignored in the wild.

2. in the ```encoding``` attribute of the ```<?xml... ?>``` xml declaration.  E.g. the following xml declaration:
```<?xml version="1.0" encoding="windows-1251"?>```
is saying that the XML document is encoded with windows-1251. Again, the encoding data in the xml declaration is not mandatory, and the spec says that the default in this case is UTF-8.

So there are two different ways the feed can tell us about encoding. None of them are mandatory and if missing they have different defaults. Worse, they can be both present but give contradictory information (I've found chinese feeds that report UTF-8 in the ```Content-type``` header but give the correct GBK encoding in the ```<?xml .. ?>``` declaration). I'm not sure which of the two should have preference, and I wouldn't trust feed owners to honor it anyway. A bit of a mess really.

What I've done in [feedbunch](http://feedbunch.com) to get around this situation is:

1. Get the encoding from the HTTP headers, if present, and ```force_encoding``` to this encoding.
2. Check if the response string is valid for that encoding with the ```xml.valid_encoding?``` method. If it returns true, I know that ruby is aware of the actual encoding of the string, so skip the next step. 
3. If ruby is mistaken about the actual encoding of the feed, try to get it from the xml declaration. Parse it with Ox and get the parsed feed encoding; Ox probably won't be able to fully parse it because of the encoding issue, but I think it will always get at least as far as parsing the xml declaration:
```
> parsed = Ox.parse xml
> encoding = parsed.encoding
> xml.force_encoding encoding
```
Now ```valid_encoding?``` should return true, otherwise that feed is probably beyond hope.

Once we've made ruby aware of the actual xml encoding with ```force_encoding```, we can pass it to Feedjira for parsing and so on. 

The above algorithm has probably room for improvement. I'm not happy with having to parse the xml to find out its encoding, in particular; probably a regex-based solution could be implemented instead. Feel free to make suggestions :)

**Comment by jonallured** [comment]
@amatriain - thanks for the explanation, very thorough!! :D

Details like this are what make building an RSS feed reader so challenging. @azangru, if you have anything further on this, just let us know!

**Comment by jonallured** [comment]
Hi @azangru, I'm going to go ahead and close this one - let me know if you're still having issues.

Thanks!
Jon

**Comment by azangru** [comment]
Hi Jon and Alfredo,

My apologies for the late response: it is only now that I discovered that you've replied to my issue. Thanks a lot to Alfredo for the detailed explanation.
