### ISSUE TITLE
Parsing RSS iTunes feed?

### ISSUE THREAD

**Issue by ruiafonsopereira** [feedjira/feedjira#285]
Using feedjira, is it possible to fetch and parse [this feed](https://itunes.apple.com/pt/rss/toppodcasts/limit=25/explicit=true/xml)? Should I use a custom parser? If so, how can I do that?
Regarding the feed, I'd like to get the fields ``title`` and ``updated``, and for each entry, I'd like to get it's ``title``, ``summary`` and
```xml
<im:image height="170">
http://is1.mzstatic.com/image/pf/us/r30/Podcasts4/v4/39/f7/47/39f74775-69e6-8c56-684f-f73ff6b1b563/mza_2252687005131610540.170x170-75.jpg
</im:image>
```

Not sure if you guys can help me.
Thanks in advance.

**Comment by amatriain** [comment]
Have you tried parsing it with Feedjira? What problem have you found? It seems to me Feedjira parses that feed just fine.

You can get the feed's title and entries' title, summary and content fields from the parsed feed object. I don't think you can get the feed's updated field that way, but you can get the updated field of the first entry, which should have the same value.

Feedjira can give you each entry's content. If you want to extract a specific <img> tag from that content you will have to implement a solution yourself, perhaps with an xml parser like nokogiri and an xpath expression.

**Comment by ruiafonsopereira** [comment]
Indeed I have.

By doing
```ruby
url = "https://itunes.apple.com/pt/rss/toppodcasts/limit=25/explicit=true/xml"
feed = Feedjira::Feed::fetch_and_parse url
```

Feedjira parses almost as I need it too. For each entry, the only missing and needed field is the image url presented in the first comment.

**Comment by amatriain** [comment]
The use of a custom parser is documented in the [project website](http://feedjira.com). Look at the "Just parsing" section and the search for "If you have the XML and just want to provide a parser class for one parse".

The [Feedjira::Parser::ITunesRSS](https://github.com/feedjira/feedjira/blob/master/lib/feedjira/parser/itunes_rss.rb) parser included in the gem is almost what you need, I think. But it doesn't really work with your feed. If you parse the feed using that parser, the resulting object has zero entries, which makes this parser unsuitable for your needs.

The reason this parser fails is that it expects the itunes XML namespace to use the ```itunes:``` prefix. Your feed, however, uses the ```im:``` prefix for this namespace. This confuses the parser and it finds no elements.

You have two options, as far as I can see:

- fix the ITunesRSS parser so that it accepts both ```itunes:``` and ```im:``` namespace prefixes in the XML, and submit a PR.
- or, do not use a custom parser, just let Feedjira automatically select one for you (in this case it uses an Atom parser, I think). Then read the ```content``` of each entry, parse it with an xml gem like Ox or Nokogiri, and extract the href of the img tag with an xpath expression.

**Comment by jonallured** [comment]
Hey @ruiafonsopereira, I'm going to close this one for now, but let us know if you're still having issues.

Thanks!
Jon
