### ISSUE TITLE
Feedjira::Feed.fetch_and_parse stopped working for array of urls

### ISSUE THREAD

**Issue by acrogenesis** [feedjira/feedjira#287]
`Feedjira::Feed.fetch_and_parse(array_of_urls)` stopped working. Is there another method or this was completely removed?

**Comment by dksaini14** [comment]
Also, NoMethodError (undefined method `fetch_raw' for Feedjira::Feed:Class):

**Comment by jonallured** [comment]
Hi @acrogenesis - with version 2.0, the API for Feedjira has changed - only a single URL should be passed. Check it out:

```ruby
for url in urls
  feed = Feedjira::Feed.fetch_and_parse url
  # do awesome stuff with feed
end
```

I hope that helps and let me know if you need anything else on this.

Thanks!
Jon

**Comment by acrogenesis** [comment]
@jonallured That does work but it is slow. The way the v1.6 did it was a lot faster.

**Comment by dksaini14** [comment]
So finally I have locked to version 1.6.0

**Comment by jonallured** [comment]
Hi @acrogenesis, one big change in version 2.0 is that Feedjira no longer provides concurrency. In earlier versions of the gem, `curb` is used to automatically fetch feeds concurrently.

For many users this was unnecessary. Feeds are fetched in worker processes using something like Resque. What I've done is remove opinions about how this should be done so that developers can make these decisions themselves.

I can't be sure about how Feedjira is being used on your project, but it sounds like the naive loop in my earlier comment isn't going to work. You might want to think about using Ruby threads or even workers depending on your use case.

Or, if like @dksaini14, you simply prefer the old behavior, feel free to lock to version 1.6.0.

**Comment by impious** [comment]
I had the same trouble the above peole had, so i will share my code.
I hope jonallured doesn't mind me messing around the closed thread but:
#please don't mind the vars name, testing
#urls is an array of strings

threads = []
arr2=[]
for x in urls
  threads << Thread.new(x) { |myFeed|
    aux=Feedjira::Feed.fetch_and_parse myFeed
    arr2.push(aux)
  }
end

threads.each { |aThread|  aThread.join }

puts 'show me the money'
arr2.each do |b|
  puts b
  puts b.title
  puts b.entries.count
  b.entries.each do |e|
    puts e.title
  end
end
