### ISSUE TITLE
I have problem when I try to load feed entries: ArgumentError

### ISSUE THREAD

**Issue by ipatovanton** [feedjira/feedjira#298]
I have problem when I try to load feed entries

```
ArgumentError (wrong number of arguments (2 for 1)):
```

I use feedjira 2.0, mongoid

```
  def load_feed_entries
    last_entry = self.feed_entries.last
    if last_entry.nil?
      feed = Feedjira::Feed.fetch_and_parse(self.url)
    else
      feed = Feedjira::Feed.fetch_and_parse(self.url,
        :if_modified_since => last_entry.published_at.to_time)
    end

    Source.add_entries(feed.entries, self.id)
  end

  def self.update_all_feeds(urls)
    Feedjira::Feed.fetch_and_parse(urls,
      :on_success => lambda { |url, feed|
        rss = Source.only(:id).where(:url => url).first
        Source.add_entries(feed.entries, rss.id)
      }
    )
  end
```

**Comment by jonallured** [comment]
Hey @ipatovanton, first off, you're getting that error because with version 2.0, `fetch_and_parse` no longer accepts two arguments. In fact, it's been changed to only support one URL at a time.

So, let's take a look at how you might approach refactoring your code:

```ruby
def load_feed_entries
  feed = Feedjira::Feed.fetch_and_parse(self.url)
  Source.add_entries(feed.entries, self.id)
end

def self.update_all_feeds(urls)
  for url in urls
    feed = Feedjira::Feed.fetch_and_parse(self.url)
    rss = Source.only(:id).where(:url => url).first
    Source.add_entries(feed.entries, rss.id)
  end
end
```

What I'd suggest is pushing down any logic about whether the entry is new or not into `add_entries` on `Source`. That's nice because then both code paths can benefit from this logic. If you're interested, I've ranted a little about why I think this should not be in Feedjira on #218.

But I would also consider what's going on with `update_all_feeds` - the fact that this method is named "all", but then also takes an argument is weird. But more than that, you had to come up with those URLs somewhere, so why not just something like this:

```ruby
Source.all.each &:load_feed_entries
```

But that'll take a while - are you using workers? I'd rather see something like this:

```ruby
class SourceUpdateWorker
  include Sidekiq::Worker

  def perform(id)
    Source.find(id).load_feed_entries
  end
end

Source.all.pluck(:id).each { |id| SourceUpdateWorker.perform_async(id) }
```

That way you have a job you can work with instead of doing things in series.

So, there are some thoughts for you - let me know if that helps!!
Jon
