### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by jonallured** [feedjira/feedjira#324]
I don't use this project anymore and haven't been the best maintainer lately. I've tried to give this gem some love, but it's just really hard with everything else going on in my life.

That's why I've opened this issue and am inviting anyone that is interested to become a maintainer of this gem. I have no idea if anyone will take me up on it, but after reading [this comment](https://github.com/feedjira/feedjira/pull/322#issuecomment-257057384) and reflecting on it, I have realized that I need help.

So, if you want to help this gem keep moving forward, simply comment that you'd like commit access and I'll add you. I hope you'll think about commenting! :heart: :heart: :heart:

**Comment by HParker** [comment]
I found this gem through a stack overflow answer about writing a rss reader with rails. I think many other folks find this gem in a similar way.

Because of that it seems like it would be worthwhile to keep this gem under active maintenance.

I am happy to help out, but I am worried that I don't understand your vision for the project or have enough domain knowledge to push the project in the right direction.

That being said if the main thing you need help with is issue triage and pull request review, I believe I could help with that.

**Comment by jonallured** [comment]
HI @HParker, I just added you!!

**Comment by PascalTurbo** [comment]
Hi There,
 
I’m now using feedjira for more than two years. We are processing a bunch of news feeds from around the world every day (10.000 at the moment – until the end of the year it will be over 20.000 feeds).
Feedjira is a great project which helps me realizing my project faster and better.
 
Beside this experience I’ll have a slightly different view on the use case of feedjira. Instead of fetching feeds for showing the results to users, I’m processing them for further analysis.

I don’t want to see the project die and I would love to support the project with my experiences made in the last two years. Also it’s clear, that our internal project will survive the next year so I’ll have the time to support feedjira.

**Comment by jonallured** [comment]
Hi @PascalTurbo, I just added you!!

**Comment by mikeastock** [comment]
Hello! I'm interested in lending a hand with maintaining Feedjira.

**Comment by jonallured** [comment]
Hi @mikeastock, I just added you!!

**Comment by mikeastock** [comment]
@jonallured would it be possible for you to add me as a collaborator on RubyGems?

**Comment by jonallured** [comment]
@mikeastock done!

**Comment by mikeastock** [comment]
Closing this for now...
