### ISSUE TITLE
Configurable parsers

### ISSUE THREAD

**Issue by mikeastock** [feedjira/feedjira#370]
How do we feel about supporting a middleware like system where people can plug and play parsers that don't match RFC's but are commonly needed? These parsers can be maintained as separate gems possibly making it clearer what does and does not belong in Feedjira? A lot of this idea was stolen from @HParker but I wanted to get a conversation going.

**Comment by mikeastock** [comment]
I would love to get @jonallured's opinion if possible.

**Comment by jonallured** [comment]
Hey @mikeastock, I have opinions and ideas, but since I'm not very active on
Feedjira anymore, the direction the project takes isn't really up to me and
that's great! This new wave of maintainers is doing an awesome job!!!

Having said that, allow me to pontificate. :smile:

While it's nice that any old Ruby script can use Feedjira, I've always
considered the main use case to be the one that brought me to Feedjira in the
first place:

> Create an RSS reader Rails app like Google Reader

The reason I don't have much time for Feedjira anymore is that I gave up
building this and decided to use Feedbin which is an awesome project that
actually uses Feedjira!

Anyway, given that use case, there are some things I assume:

* A user probably wants to configure Feedjira in an initializer
* A user is probably parsing feeds in a job
* A user probably has some trouble feeds where the default parsers don't work

Does that seem like a reasonable list? Did I miss anything big? How does
Feedjira do if judged by those requirements?

I don't know, good? Needs improvement?

Here's what I always wanted to do, but never got around to:

```ruby
# config/initializers/feedjira.rb
Feedjira::Config do |config|
  config.parsers = [
    # define parser order here, maybe inserting some general custom parsers
  ]
end
```

```ruby
# app/jobs/feed_parser_job.rb
class FeedParserJob < ApplicationJob
  def perform(feed_id)
    feed = Feed.find feed_id
    xml = Faraday.get feed.url
    parsed_feed = FeedParser.parse feed, xml
    FeedUpdater.update feed, parsed_feed
  end
end
```

```ruby
# app/models/feed.rb
class Feed < ApplicationRecord
  # * url - string, required: 'http://daringfireball.net/feeds/main'
  # * parser_klass - string, optional: 'DaringFireballParser'
end
```

```ruby
# app/models/feed_parser.rb
class FeedParser
  def self.parse(feed, xml)
    new(feed, xml).parse
  end

  def initialize(feed, xml)
    @feed = feed
    @xml = xml
  end

  def parse
    parser_klass.parse @xml
  end

  private

  def parser_klass
    @feed.parser_klass.empty? ? default_parser : @feed.parser_klass.constantize
  end

  def default_parser
    Feedjira.parser_for_xml @xml
  end
end
```

```ruby
# app/models/feed_updater.rb
class FeedUpdater
  def self.update(feed, parsed_feed)
    # some lit ass code :fire:
  end
end
```

```ruby
# app/parsers/daring_fireball_parser.rb
class DaringFireballParser < Feedjira::Parser
  # Grab the url to the post on df.net, not the site he links to.
  # Or whatever custom behavior you like.
  # Or more likly, code to fix some horseshit.
end
```

Does this make sense? It's a rough sketch, just trying to convey ideas. Here are
some highlights:

* Configure in a idiomatic way
* Custom parser are likely, parser order may change
* Feed-specific parsers are inevitable
* Speed in parsing XML hardly matters
* Concurrency is dealt with by using jobs
* Exceptions are fine - failed jobs are ok
* Fetching XML should not be a part of Feedjira
* Kill that damn `Feedjira::Feed` class!

Hope this provides some value!! :heart: :heart: :heart:

**Comment by HParker** [comment]
Thanks so much. That matches what I would expect as well.

It would also be nice to have rails style `add_parser_after` `delete_parser` helpers, but not something needed in a first go at configuration.

**Comment by mikeastock** [comment]
Thanks for the input @jonallured! This is exactly in align with what I have actually started building.
